version = 4.1.1
archive_dir = /etc/letsencrypt/archive/temporal-game.inesctec.pt
cert = /etc/letsencrypt/live/temporal-game.inesctec.pt/cert.pem
privkey = /etc/letsencrypt/live/temporal-game.inesctec.pt/privkey.pem
chain = /etc/letsencrypt/live/temporal-game.inesctec.pt/chain.pem
fullchain = /etc/letsencrypt/live/temporal-game.inesctec.pt/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = c3a9418747d568d800e430b764f3fda9
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
